### ISSUE TITLE
Based on doc example, simply does not work

### ISSUE THREAD

**Issue by micahblu** [shakyShane/browser-sync#406]
I followed the docs and I have a simple folder with an index.html and a gulp file containing code from the docs, however, when I run gulp I get a browser window showing me the index.html yet when I edit index.html it does not update?

```javascript
var gulp = require('gulp'),
    browserSync = require('browser-sync');

gulp.task('browser-sync', function() {
  browserSync({
    server: {
      baseDir: "./"
    }
  });
});
```

**Comment by faergeek** [comment]
You need to specify files to watch, like this:

```javascript
var gulp = require('gulp'),
    browserSync = require('browser-sync');

gulp.task('browser-sync', function() {
  browserSync({
    server: {
      baseDir: "./"
    },

    files: [
      "css/**/*.css",
      "js/**/*.js",
      "index.html"
    ]
  });
});
```

But documentation should be fixed anyway.

**Comment by micahblu** [comment]
Thanks, but still no luck, on adding the files param, I see that bs does detect the file however the browser page does not reload.

**Comment by shakyShane** [comment]
Have you checked https://github.com/shakyShane/browser-sync#requirements

**Comment by micahblu** [comment]
That did it, my index.html was lacking a body tag. I just quickly typed up a `<h1>Hello World</h1>` to test. Thanks for the help
